### ISSUE TITLE
UUID not resolved after ID change

### ISSUE THREAD

**Issue by jGleitz** [vitruv-tools/Vitruv#175] opened 2017-10-17 09:40 UTC
I found this while trying to figure out why my tests don’t work. It probably needs further investigation (after I finished my thesis), but right now it looks like a bug in the UUID mechanism to me:

After an attribute change, the changed `EObject` notifies the registered adapter `tools.vitruv.framework.change.recording.NotificationRecorder`, which lets `tools.vitruv.framework.change.recording.NotificationToEChangeConverter` convert it. The converter tries to get the object’s UUID and calls `tools.vitruv.framework.change.echange.EChangeIdManager#setOrGenerateIds`. This will, in effect, lead to a call of `tools.vitruv.framework.change.echange.EChangeIdManager#registerGlobally`, which will try to retrieve the object using its URI as generated by  `EcoreUtil#getURI`.

Now a problem arises if the changed attribute is an ID attribute and thus influences the URI: The calculated URI contains the new value of the ID attribute, while the resource still contains an old copy of the object, with an old ID. Line 121 in `tools.vitruv.framework.change.echange.EChangeIdManager` hence throws an exception:

```
java.lang.IllegalStateException: Object has no UUID and is not globally accessible: allElementTypes.impl.RootImpl@44b6dbe4 (id: 2nd id) (singleValuedEAttribute: 0, singleValuedPrimitiveTypeEAttribute: 0, singleValuedUnsettableEAttribute: <unset>, multiValuedEAttribute: [], multiValuedUnsettableEAttribute: [])
```
<details>
<summary>Stack Trace</summary>

```
	at tools.vitruv.framework.change.echange.EChangeIdManager.registerGlobally(EChangeIdManager.java:121)
	at tools.vitruv.framework.change.echange.EChangeIdManager.getOrGenerateValue(EChangeIdManager.java:98)
	at tools.vitruv.framework.change.echange.EChangeIdManager._setOrGenerateAffectedEObjectId(EChangeIdManager.java:175)
	at tools.vitruv.framework.change.echange.EChangeIdManager.setOrGenerateAffectedEObjectId(EChangeIdManager.java:186)
	at tools.vitruv.framework.change.echange.EChangeIdManager.setOrGenerateIds(EChangeIdManager.java:65)
	at tools.vitruv.framework.change.recording.NotificationToEChangeConverter.handleSetAttribute(NotificationToEChangeConverter.java:411)
	at tools.vitruv.framework.change.recording.NotificationToEChangeConverter.convert(NotificationToEChangeConverter.java:65)
	at tools.vitruv.framework.change.recording.NotificationRecorder.notifyChanged(NotificationRecorder.java:59)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at allElementTypes.impl.IdentifiedImpl.setId(IdentifiedImpl.java:88)
	at tools.vitruv.dsls.commonalities.ui.executiontests.IdentifiedExecutionTest.lambda$11(IdentifiedExecutionTest.java:131)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at tools.vitruv.dsls.commonalities.ui.executiontests.IdentifiedExecutionTest.setSimpleAttribute(IdentifiedExecutionTest.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:181)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:24)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:54)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:46)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```
</details>

I don’t understand while there are multiple instances of the same model object. It might be an error in the tests but I find that unlikely, as they just use the usual EMF methods to get model objects.

After all, I feel like the error lies in the execution order: Maybe changes need to be applied to the model objects in the VSUM before UUIDs can be resolved for the objects. But my understanding is limited.

**Comment by HeikoKlare** [comment] 2017-10-17 11:50
That sounds weird. The method `registerGlobally` should only be called by `tools.vitruv.framework.change.echange.EChangeIdManager#setOrGenerateIds` if the object has to be registered globally, which is only the case for third party elements that are not contained in the VSUM (e.g. static PCM libraries with primitive types). 
I think there is a bug in the implementation, which we have to investigate.

**Comment by jGleitz** [comment] 2017-10-17 12:43
I get the same error when trying to remove a model object that I have created:

```
java.lang.IllegalStateException: Object has no UUID and is not globally accessible: allElementTypes.impl.RootImpl@877b8d6 (id: second) (singleValuedEAttribute: 0, singleValuedPrimitiveTypeEAttribute: 0, singleValuedUnsettableEAttribute: <unset>, multiValuedEAttribute: null, multiValuedUnsettableEAttribute: null)
```
<details>
<summary>Stack Trace</summary>

```
	at tools.vitruv.framework.change.echange.EChangeIdManager.registerGlobally(EChangeIdManager.java:121)
	at tools.vitruv.framework.change.echange.EChangeIdManager.getOrGenerateValue(EChangeIdManager.java:98)
	at tools.vitruv.framework.change.echange.EChangeIdManager.setOrGenerateOldValueId(EChangeIdManager.java:143)
	at tools.vitruv.framework.change.echange.EChangeIdManager.setOrGenerateIds(EChangeIdManager.java:70)
	at tools.vitruv.framework.change.recording.NotificationToEChangeConverter.handleRemoveRootChange(NotificationToEChangeConverter.java:371)
	at tools.vitruv.framework.change.recording.NotificationToEChangeConverter.handleResourceChange(NotificationToEChangeConverter.java:341)
	at tools.vitruv.framework.change.recording.NotificationToEChangeConverter.convert(NotificationToEChangeConverter.java:131)
	at tools.vitruv.framework.change.recording.NotificationRecorder.notifyChanged(NotificationRecorder.java:59)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.dispatchNotification(NotifyingListImpl.java:261)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.remove(NotifyingListImpl.java:713)
	at org.eclipse.emf.common.util.AbstractEList.remove(AbstractEList.java:464)
	at org.eclipse.emf.ecore.util.EcoreUtil.remove(EcoreUtil.java:3310)
	at org.eclipse.emf.ecore.util.EcoreUtil.delete(EcoreUtil.java:3385)
	at tools.vitruv.dsls.commonalities.ui.executiontests.IdentifiedExecutionTest.rootDelete(IdentifiedExecutionTest.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:181)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:24)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:54)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:46)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by SofiaAnanieva** [comment] 2017-11-09 15:19
In the context of intramodelconsistency, we also get the same error when (re)moving a model object and will investigate this further

**Comment by SofiaAnanieva** [comment] 2017-11-10 09:12
@FabiScheytt The warning _Object is not statically accessible but also has no globally mapped UUID_ seems to occur in different cases when creating a CAEX model via the default tree editor and saving the changes: 

- **Whenever a reaction is performed** (e.g. change name of prototype -> update of clones' reference) Object is not statically accessible but also has no globally mapped UUID: _CAEX.impl.DocumentRootImpl@70965b9f (mixed: [CAEX:cAEXFile=CAEX.impl.CAEXFileImpl@5fab3e4f (changeMode: <unset>) (fileName: filename, schemaVersion: <unset>)])_
- Moving ANY element 
- Sometimes (?) when creating an InternalHierarchy and respective InternalElements

Now, deleting any object or arbitrary changes after having moved an object leads to an _IllegalStateException_ at the UuidGeneratorAndResolverImpl.getEObject (due to EObject = null)

From here on, any arbitrary change performed and saved on the CAEX model leads to the same IllegalStateException.

**Comment by HeikoKlare** [comment] 2017-12-12 12:27
I think I was able to identify the problem: 
Whenever an object is removed from its container, the `UuidResolver` tries to find the `UUID` for the object in the global cache, where it has to resolve the `EObject`. This will always fail because the object's `URI`, which is used for resolution, has changed due to the removal.
If the global resolution fails, the local cache is used. If the element that is removed was added to that cache, this will be successfull (as it is in the existing tests) because the `EObject` itself is used to get the `UUID` from a `Map`. If you remove the element from another instance of the model than the one used for the `ChangeRecorder` (and therefore the local UUID cache), the object is also resolved by its `URI`, which fails due to the same reason than the global resolution.

We could try to maintain our position that modifications must always come from the model instance for which the local cache was created (and load that cache from the `VirtualModel´ whenever loading a model), but we will potentially still run into problems with that approach.

My current idea is to somehow use the change information, which also contains the old container object, to restore the `URI` before removing the object. Then it would be possible to correctly resolve the object. I will investigate if it is possible to calculate a kind of virtual `URI` given an object and its container. This avoids that we have to temporarily rollback the change.

**Comment by SofiaAnanieva** [comment] 2017-12-12 13:36
Thanks a lot for the investigation! So according to your idea, we would circumvent the problem of a changed URI (due to removal) by calculating a virtual URI which would be identical to the original one? 

Use-cases which lead to this problem involve the deletion of an element or moving an element, e.g., along a hierarchy (which can be directly done in the editor). If I understand correctly, the proposed solution would work for any use-case whenever an object is removed from its container.

**Comment by HeikoKlare** [comment] 2017-12-12 13:50
> So according to your idea, we would circumvent the problem of a changed URI (due to removal) by calculating a virtual URI which would be identical to the original one?
That was the basic idea, yes. Unfortunately, the technical realization is a little more difficult since we do not map `URIs` but `EObjects` to `UUIDs`, so we have to somehow find the object in our map that represents the one removed from its container. We could try to make a brute force search, but I would only use that as a fallback. I currently try a solution that finds the original object in its container in a model which is still in the old state before removing the object (in most cases the model in the `VirtualModel`) and use it for `UUID` resolution. 

> If I understand correctly, the proposed solution would work for any use-case whenever an object is removed from its container.
Exactly.

Btw: Have you documented your problems in the CAEX application with some tests? It would be a easier for me to debug the problem using your `Reactions` than the `Commonalities` written by @jGleitz because they only introduce one indirection instead of two.

**Comment by SofiaAnanieva** [comment] 2017-12-12 14:39
Thanks for explaining.
Unfortunately, all of our current tests pass ( ;-) ), but we will provide a test which documents the problem.

**Comment by HeikoKlare** [comment] 2017-12-12 16:11
Hm, very tricky issue.
The proposed solution seems to work (at least in most cases) for simple object removals, but not for recusive ones. In that case, the container of recursively removed objects can also not be resolved...

**Comment by SofiaAnanieva** [comment] 2017-12-12 16:23
Sounds like a dead end. Do you mean, for example, that if object A is removed and, according to some reaction, object B should be removed, it is not possible to resolve the container of object B?

**Comment by HeikoKlare** [comment] 2017-12-12 16:33
No, the problem is that if you remove an object B contained in A then you can simply get the old B from an old A (which you can retrieve because the URI of A did not change). But B can also contain further objects, which you cannot retrieve from an old B because you do not know an old B as it was removed from its container. You can make some recursive search in a model that has the old state before the change, but that will take some time to implement.

**Comment by HeikoKlare** [comment] 2017-12-13 10:30
I probably found a rather simple solution for the problem: If we rely on the assumption that all objects that are modified are registered in the `UuidResolver` (the objects themselves, not equal ones), we can simply use the Map in the resolver to get the `Uuid`, even if the element was removed (as its identity is still the same).
This assumption does not hold in our current scenarios, because in our Reactions and Commonalities tests, other models instances, whose `EObjects` are not mapped to `Uuids` in the local resolver, are modified, so that the resolver has to resolve the object in its `ResourceSet` first, which fails due to the discussed reasons (changes URI). However, all modified elements get registered in the `AtomicEmfChangeRecorder` first (otherwise we not get any information about changes), so we can simply add them to the local resolver map in the moment when they are registered at the recorder. In consequence, our initial assumption holds again, making the resolution process rather simple.

My initial tests with that approach are promising. Nevertheless, we will have to make some improvements afterwards as this can have a major performance impact if the models are large.

**Comment by SofiaAnanieva** [comment] 2017-12-13 12:26
First tests within the editor are as well promising! The described use-cases above do not result in the IllegalStateException anymore. However, our reaction regarding a consequential removal of an element does no work; we will investigate this further, but it seems to be some minor issue.

Thank you for the quickly implemented solution! Performance is indeed a factor which was also discussed within the last integrate meeting. We can have a chat about the outcome of the discussion later on.

**Comment by HeikoKlare** [comment] 2017-12-13 12:33
Thanks for the quick response! I just started a PR to get the fix in our master branch, which will also close this issue.
If your remaining problem is still induced by UUID errors, just start another issue for it. However, it may be some other problem not related to UUIDs.

**Closed** 2017-12-13 12:45 UTC
Labels: bug
